# Generated by Django 5.0.4 on 2024-04-17 08:42

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fields',
            field=models.JSONField(default=projects.models.default_fields),
        ),
    ]
