# Generated by Django 5.0.4 on 2024-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='component_path',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
