version: '3.8'
services:
  webscraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/webscraper
    ports:
      - "8002:8002"
    working_dir: /usr/src/webscraper
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
    - webscraper_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./static:/usr/src/app/static:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webscraper
    restart: always
    networks:
      - webscraper_network

  redis:
    image: redis:6
    ports:
      - "6380:6379"
    restart: always    
    networks:
      - webscraper_network
    volumes:
      - ./redis_app/redis.conf:/usr/local/etc/redis/redis.conf 
      - ./logs/redis.log:/var/log/redis/redis.log
    command: redis-server /usr/local/etc/redis/redis.conf


  celery:
    build:
      context: .
      dockerfile: ./celery_app/Dockerfile
    command: celery -A webscraper worker --loglevel=debug
    restart: always
    depends_on:
      - redis
    networks:
      - webscraper_network
    volumes:
      # - ./logs:/app/logs
      # - ./scrapers:/app/scrapers
      # - ./celery_app:/app/celery_app
      # - .scraped_data.sqlite3:/app/scraped_data.sqlite3
      - .:/app/

  tailwind:
    tty: true
    restart: always
    build:
      context: ./
      dockerfile: ./tailwind/Dockerfile
    volumes:
      - ./static/:/static
      - ./:/webscraper
    networks:
    - webscraper_network

  stimulus:
    restart: always
    build:
      context: ./
      dockerfile: ./stimulus/Dockerfile
    volumes:
      - ./stimulus/controllers:/controllers
      - ./static/js/stimulus:/static/js/stimulus
    networks:
    - webscraper_network

networks:
  webscraper_network:
    driver: bridge
